flicker_craigslist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Applications
    path('', include('my_app.urls')),
]

# Static files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_search/', views.new_search, name='new_search'),
]

my_app/models.py
from django.db import models


class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.search

    class Meta:
        verbose_name = 'Search'
        verbose_name_plural = 'Searches'

my_app/views.py
import requests
from requests.compat import quote_plus
from django.shortcuts import render
from bs4 import BeautifulSoup
from django.views.decorators.csrf import csrf_exempt

from . import models

BASE_CRAIGSLIST_URL = 'https://jaipur.craigslist.org/d/for-sale/search/sss?query={}'
BASE_IMAGE_URL = 'https://images.craigslist.org/{}_300x300.jpg'


def home(request):
    return render(request, 'base.html')


@csrf_exempt
def new_search(request):
    search = request.POST.get('search')
    models.Search.objects.create(search=search)
    final_url = BASE_CRAIGSLIST_URL.format(quote_plus(search))
    response = requests.get(final_url)
    data = response.text
    soup = BeautifulSoup(data, features='html.parser')

    post_listings = soup.find_all('li', {'class': 'result-row'})

    final_postings = []

    for post in post_listings:
        post_title = post.find(class_='result-title').text
        post_url = post.find('a').get('href')

        if post.find(class_='result-price'):
            post_price = post.find(class_='result-price').text
        else:
            post_price = "N/A"

        if post.find(class_='result-image').get('data-ids'):
            post_image_id = post.find(
                class_='result-image').get('data-ids').split(',')[0].split(':')[1]
            post_image_url = BASE_IMAGE_URL.format(post_image_id)
        else:
            post_image_url = 'https://craigslist.org/image/peace.jpg'

        final_postings.append(
            (post_title, post_url, post_price, post_image_url)
        )

    stuff_for_frontend = {
        'search': search,
        'final_postings': final_postings,
    }
    return render(request, 'my_app/new_search.html', stuff_for_frontend)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flicker Craigslist</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
    <nav class="nav-wrapper">
        <div class="container">
            <a href="{% url 'my_app:home' %}" class="brand-logo">Flicker Craigslist</a>

            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'my_app:home' %}">Home</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h1 style="text-align: center;">What do you want to search for on Flicker Craigslist List?</h1>
        <div class="row">
            <div class="col s4">
                <div class="center">
                    <i class="large material-icons" style="color: #EE6E73;">flash_on</i>
                    <p>Fast craigslist web scraper</p>
                    <p class="light center">Scrape away right here with a beautiful GUI.</p>
                </div>
            </div>

            <div class="col s4">
                <div class="center">
                    <i class="large material-icons" style="color: orange;">camera</i>
                    <p>Filter your searches</p>
                    <p class="light center">We built in functionality to filter based on pricing.</p>
                </div>
            </div>

            <div class="col s4">
                <div class="center">
                    <i class="large material-icons" style="color: blue;">chrome_reader_mode</i>
                    <p>A much sexier front-end to Craigslist</p>
                    <p class="light center">We built this with 💓.</p>
                </div>
            </div>
        </div>

        <form action="{% url 'my_app:new_search' %}" method="POST">
            {% csrf_token %}

            <input type="text" name="search" placeholder="Search">

            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>

        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>

templates/my_app/new_search.html
{% extends 'base.html' %}

{% block content %}

<h2 style="text-align: center;">{{ search|title }}</h2>

<div class="row">
    {% for post in final_postings %}

    <div class="col s4">
        <div class="card">
            <div class="card-image">
                <a href="{{ post.1 }}"><img src="{{ post.3 }}" alt="Oops!!! Image not found..."></a>
            </div>
            <div class="card-content">
                <p>{{ post.0 }}</p>
            </div>
            <div class="card-action">
                <a href="{{ post.1 }}">View listing: Price {{ post.2 }}</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock content %}